# Generated by Django 3.0.4 on 2020-04-30 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GLUG', '0008_delete_listofproject'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listOf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GLUG.Project')),
            ],
        ),
    ]
