# Generated by Django 3.0.4 on 2020-05-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_listof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listOf',
        ),
    ]
