# Generated by Django 3.0.4 on 2020-05-02 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_listof'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofproject',
            name='icon',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
