# Generated by Django 3.0.4 on 2020-05-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_listofproject_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofproject',
            name='icon',
        ),
    ]
