# Generated by Django 3.0.6 on 2020-05-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0008_delete_listofproject'),
        ('accounts', '0006_milestoneobjects_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestoneobjects',
            name='milestones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GLUG.Project'),
        ),
        migrations.DeleteModel(
            name='Milestones',
        ),
    ]
