# Generated by Django 3.0.4 on 2020-03-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='des',
            new_name='description',
        ),
    ]
