# Generated by Django 3.0.4 on 2020-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0002_auto_20200329_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
