# Generated by Django 3.0.4 on 2020-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.TextField(),
        ),
    ]
