# Generated by Django 3.0.4 on 2020-03-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0004_auto_20200329_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
