# Generated by Django 3.0.4 on 2020-04-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GLUG', '0007_listofproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='listOfProject',
        ),
    ]
